import { useAtomValue } from 'jotai';
import {
  availabilityAtom,
  bodyAtom,
  carBrandIdAtom,
  carPartIdAtom,
  conditionAtom,
  countItemsAtom,
  discBrandIdAtom,
  discDiaAtom,
  discDiameterAtom,
  discEjectionAtom,
  discHolesAtom,
  discModelAtom,
  discPcdAtom,
  discWidthAtom,
  fuelAtom,
  gearboxAtom,
  isPrintedStatusAtom,
  priceFromAtom,
  priceToAtom,
  seriesIdAtom,
  tiresBrandIdAtom,
  tiresCarTypeAtom,
  tiresDiameterAtom,
  tiresHeightAtom,
  tiresIndexAtom,
  tiresModelAtom,
  tiresResidueFromAtom,
  tiresResidueToAtom,
  tiresSeasonAtom,
  tiresWidthAtom,
  yearFromAtom,
  yearToAtom,
} from '../../..';

export const useFilterCategories = () => {
  return {
    condition: "used",
    fuel: useAtomValue(fuelAtom),
    body: useAtomValue(bodyAtom),
    gearbox: useAtomValue(gearboxAtom),
    countItems: useAtomValue(countItemsAtom),
    carBrandId: useAtomValue(carBrandIdAtom),
    seriesId: useAtomValue(seriesIdAtom),
    isPrintedStatus: useAtomValue(isPrintedStatusAtom),
    carPartId: useAtomValue(carPartIdAtom),
    yearFrom: useAtomValue(yearFromAtom)?.toString().trim(),
    yearTo: useAtomValue(yearToAtom)?.toString().trim(),
    priceFrom: useAtomValue(priceFromAtom)?.toString().trim(),
    priceTo: useAtomValue(priceToAtom)?.toString().trim(),
    availability: useAtomValue(availabilityAtom),
    discDiameter: useAtomValue(discDiameterAtom),
    discWidth: useAtomValue(discWidthAtom)?.toString(),
    discEjection: useAtomValue(discEjectionAtom)?.toString(),
    discDia: useAtomValue(discDiaAtom)?.toString(),
    discHoles: useAtomValue(discHolesAtom)?.toString(),
    discModel: useAtomValue(discModelAtom),
    discPcd: useAtomValue(discPcdAtom)?.toString(),
    discBrandId: useAtomValue(discBrandIdAtom),
    tiresDiameter: useAtomValue(tiresDiameterAtom),
    tiresSeason: useAtomValue(tiresSeasonAtom),
    tiresWidth: useAtomValue(tiresWidthAtom)?.toString(),
    tiresHeight: useAtomValue(tiresHeightAtom)?.toString(),
    tiresIndex: useAtomValue(tiresIndexAtom)?.toString(),
    tiresCarType: useAtomValue(tiresCarTypeAtom),
    tiresModel: useAtomValue(tiresModelAtom),
    tiresBrandId: useAtomValue(tiresBrandIdAtom),
    tiresResidueFrom: useAtomValue(tiresResidueFromAtom)?.toString(),
    tiresResidueTo: useAtomValue(tiresResidueToAtom)?.toString()
  };
};
